### PR TITLE
add additional YAMLs to project root with stable and dev versions

### LINKED ISSUE #23: add a `-stable` YAML file at the repository root that constrains versions to stable
this should be alongside the current `-latest` YAML file, and GitHub Actions should also build environments for this as well

### PR DESCRIPTION
**Pull request by zacharyburnett**
closes #23

### CODE REVIEW

**Comment by zacharyburnett** [comment]
@nden suggested that we do not need to release `stable` with every release, only once every quarter. This means that we could possibly make building `stable` conditional upon some label or marker in the release (possibly like an `lts` string in the tag)

**Comment by nden** [comment]
Looking at `stenv-stable.yml` I agree this is the sane and reasonable thing to do. I'm a bit concerned though that we have not had the discipline to use semantic versioning consistently in the past. Unless this changes if a backwards incompatible version of a package is released as a patch this may break the distribution. @jhunkeler What do you think based on your experience?

**Comment by zacharyburnett** [comment]
> Unless this changes if a backwards incompatible version of a package is released as a patch this may break the distribution.

Perhaps to mitigate this we can add another scheduled CI to this repository that tests all packages at their latest development versions from Git, and then make sure to check the status of that when updating upstream packages.

**Comment by zacharyburnett** [comment]
Ok, I separated the original `build.yml` into `build_latest.yml`, `build_stable.yml`, and `build_dev.yml`. They are triggered as follows:
### `build_latest.yml`
- on pull requests to `main` **only when YAML files are updated**
- on a published release (attaches exported files to the release)
- on manual dispatch
https://github.com/spacetelescope/stenv/blob/28338584399359ded2e5d7a57e41dc16f7941dfb/.github/workflows/build_latest.yml#L3-L12
### `build_stable.yml`
- on a published release **with a tag containing `stable`** (attaches exported files to the release)
- on manual dispatch
https://github.com/spacetelescope/stenv/blob/28338584399359ded2e5d7a57e41dc16f7941dfb/.github/workflows/build_stable.yml#L3-L9
### `build_dev.yml`
- on a schedule, at midnight daily
- on a published release (attaches exported files to the release)
- on manual dispatch
https://github.com/spacetelescope/stenv/blob/28338584399359ded2e5d7a57e41dc16f7941dfb/.github/workflows/build_dev.yml#L3-L9

**Comment by jhunkeler** [comment]
> Looking at `stenv-stable.yml` I agree this is the sane and reasonable thing to do. I'm a bit concerned though that we have not had the discipline to use semantic versioning consistently in the past. Unless this changes if a backwards incompatible version of a package is released as a patch this may break the distribution. @jhunkeler What do you think based on your experience?

Unfortunately there isn't much you can do except deal with the compatibility issues as they occur and remind developers to start bumping their major versions after committing breaking changes to projects, even if they believe they're the only ones using the code. Failures in `-stable` are **usually** easy to remedy. It'll become a nightmare when one of our maintainers decides to incorporate a recently minted package as a dependency, or a language feature only found in the latest Python interpreter. The latter happened frequently when 3.6 debuted and people started using `f"{variable}"` format strings. Compatibility with 3.5 dropped off overnight and obviously lead to build errors and delays because at the time we "couldn't" upgrade away from 3.5 in OPS for "reasons".

The `-dev` YAML file does make for a good weather report to see which of our packages require immediate attention, however beyond that it'll become noise to anyone subscribed to this repository. Noise tends to get shoveled off to the "Deleted Items" folder.

I'm sure you remember the first rule about `conda-dev` and why we didn't want people to use it, right? The constant build failures were masked by Jenkins' horrible interface and our (my) intentional lack of advertising. Trust me though... this thing was a broken awful mess and required a lot of face-to-desk to keep up with it.

I have a question for @zacharyburnett. Couldn't the testing phases be abstracted away into a series of shell scripts, or offloaded to a loop in a single shell script instead of hard coding it all into the YAML file?

``` yaml
# psuedo GHA config

matrix:
  testing:
    packages: [a, b, c, d]
    env:
      pytest_args: { os.only.defined.once.pytest_args }

    run:  
      - ./ci/a_script.sh {package_here}
```

```shell
#!/usr/bin/env bash

git clone --recursive "$1"
pushd $1
    pytest $pytest_args .
popd
```

or

```shell
#!/usr/bin/env bash

for package in $*; do
    git clone --recursive "$1"
    pushd $1
        pytest $pytest_args .
    popd
done
```

**Comment by zacharyburnett** [comment]
> The -dev YAML file does make for a good weather report to see which of our packages require immediate attention, however beyond that it'll become noise to anyone subscribed to this repository. Noise tends to get shoveled off to the "Deleted Items" folder.

Good point, we can probably drop the scheduled daily run (and also the release trigger) and have the `dev` workflow only run on manual dispatch; that would ensure that people run it as-needed and pay attention to the results.

> Couldn't the testing phases be abstracted away into a series of shell scripts, or offloaded to a loop in a single shell script instead of hard coding it all into the YAML file?

We definitely could do that, but would lose the nice individual checks on the CI dashboard (as well as any console output for individual failures). Were you thinking of making it so that someone could run the tests locally?

**Comment by jhunkeler** [comment]
The thought hadn't crossed my mind about local testing. A lot of our packages tend to chew up more resources than the average desktop or laptop has anyway. I approaching it more from a readability and long-term maintenance standpoint. It's a lot of duplicate instructions spread across multiple configs. I'm sure you can still achieve the same level of job granularity. I was thinking for the sake of readability just offload the chunkier `run:` statements to various scripts housed in the repo.

**Comment by zacharyburnett** [comment]
I've consolidated the workflows back into a single YAML file, and made it so that `stable` and `dev` builds can be triggered manually. Then, exported `stable` files can be added to the release.

**Comment by nden** [comment]
@jhunkeler Is more work needed here? Is it ready to merge?

**Comment by zacharyburnett** [comment]
> `stenv-stable.yml` is missing several pins though (notably `hstcal` and `fitsverify`)

Oh you're right, what versions should those be pinned to? As they are on `conda-forge`, do they get updated often?

> It's an executive decision whether `jupyter` and `dask` are always going to pick up the latest version at release time. If tests pass then I suppose that's good enough, right?

I figure that these are moreso constrained by the individual packages that are using them, or by the user. If a newer version of `dask` breaks functionality for one of its downstream `spacetelescope` packages then IMO I think that package should specify the constraint in its own build config instead of here.

**Comment by jhunkeler** [comment]
I see you found the versions :sweat_smile: 

>I figure that these are moreso constrained by the individual packages that are using them, or by the user. If a newer version of dask breaks functionality for one of its downstream spacetelescope packages then IMO I think that package should specify the constraint in its own build config instead of here.

If these were pure conda packages I'd have to disagree because someone is always breaking recipes upstream, however I agree... for pip this approach makes perfect sense. :+1:

**Comment by zacharyburnett** [comment]
alright, then an approval and we can merge this in!

**Review by jhunkeler — APPROVED** [review]
:rocket:

**Pull request merged**
